displayName=Goal Tracker
author=Darkforge317
support=https://github.com/Darkforge317/rl-goal-tracker
description=Track and organize RuneScape goals with progress bars, presets, and more.
tags=task,to-do,todo,Track,organize,progress
plugins=com.darkforge317.goaltracker.GoalTrackerPlugin
version=2.1.1
build=standard
